In [2]:
import numpy as np

In [4]:
# Creating a 1D Array

arr = np.array([1,2,3,4])
print("The 1D array is as given ",arr)
print(type(arr))
print(arr.shape)


The 1D array is as given  [1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [6]:
# Dimensions of a array

# 2 rows,4 cols
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
# Inbuilt array functions

# Get the numbers between 0 and 10 with 2 steps diff
# then reshape to 5 rows and 1 col
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
# Generate the array of 3 rows and 1 col
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Identity Matrix of size 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Attributrs of a numpy array

arr3 = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr3)
print("Shape:",arr3.shape)
print("Number of dimensions:",arr3.ndim)
print("Size (number of elements):",arr3.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)



Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [16]:
# Vectorized Operations of Numpy

arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition: ",arr4+arr5)

# Element wise Substraction
print("Subtraction: ",arr5-arr4)

# Element wise Multiplication
print("Multiplication: ",arr4*arr5)

# Element wise Division
print("Division: ",arr4/arr5)





Addition:  [11 22 33 44 55]
Subtraction:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
# Universal Functions

arr6 = np.array([2,3,4,5,6])

# Square Root
print(np.sqrt(arr6))

# Exponential 
print(np.exp(arr6))

# Sine
print(np.sin(arr6))

# Natural Log
print(np.log(arr6))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
# Array Slicing & Indexing

arr7 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr7)

# Accessing 1 which is present in first row and first col
print(arr7[0][1])

# Fetching the numbers 7,8,,11,12
print(arr7[1:,2:])

# Fetching the numbers 3,4,7,8
print(arr7[0:2,2:])

# Fetching the numbers 6,7,10,11
print(arr7[1:,1:3])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [ ]:
# Modify Array Elements

arr7[0,0] = 100
print(arr7)

print("\n")

# Replace all the elements from second row as 100
arr7[1:] = 100
print(arr7)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [36]:
# Statistical Concepts --> Normalization
# Means having a mean of 0 and S.D of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and std deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean)/std_dev
print("The Normalized Data: ",normalized_data)



The Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data2 = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data2)
print("Mean: ",mean)

# Median
median = np.median(data2)
print("Median: ",median)

# Std Deviation
std_dev2 = np.std(data2)
print("Standard Deviation: ",std_dev2)

# Variance
variance = np.var(data2)
print("Variance: ",variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [42]:
# Logical Operations
data3 = np.array([1,2,3,4,5,6,7,8,9,10])

# Fetch the data greater than 5
print(data3[data3 > 5])

# Fetch the data greater than 5 and data less than 8
print(data3[(data3 >= 5) & (data3 <= 8)])

[ 6  7  8  9 10]
[5 6 7 8]
